/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountButton: typeof import('./components/AccountButton.vue')['default']
    AccountDropDown: typeof import('./components/AccountDropDown.vue')['default']
    AccountPopup: typeof import('./components/AccountPopup.vue')['default']
    BasketButton: typeof import('./components/BasketButton.vue')['default']
    Car: typeof import('./components/Car.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    Carusel: typeof import('./components/Carusel.vue')['default']
    Carusel2: typeof import('./components/Carusel2.vue')['default']
    MenuButton: typeof import('./components/MenuButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./components/Slide.vue')['default']
    UndefinedWelcome: typeof import('./components/UndefinedWelcome.vue')['default']
  }
}
