/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountButton: typeof import('./components/AccountButton.vue')['default']
    AccountDropDown: typeof import('./components/AccountDropDown.vue')['default']
    AccountPopup: typeof import('./components/AccountPopup.vue')['default']
    BasketButton: typeof import('./components/BasketButton.vue')['default']
    BasketItem: typeof import('./components/BasketItem.vue')['default']
    BasketItemButton: typeof import('./components/BasketItemButton.vue')['default']
    BasketItems: typeof import('./components/BasketItems.vue')['default']
    BasketRemoveItemButton: typeof import('./components/BasketRemoveItemButton.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    Carusel: typeof import('./components/old/Carusel.vue')['default']
    ChangePasswordForm: typeof import('./components/ChangePasswordForm.vue')['default']
    ErrorPopup: typeof import('./components/ErrorPopup.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormFilterCards: typeof import('./components/FormFilterCards.vue')['default']
    MenuButton: typeof import('./components/MenuButton.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Order: typeof import('./components/Order.vue')['default']
    OrderAddressForm: typeof import('./components/OrderAddressForm.vue')['default']
    OrderItems: typeof import('./components/OrderItems.vue')['default']
    RepeatOrderButton: typeof import('./components/RepeatOrderButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetailsButton: typeof import('./components/ShowDetailsButton.vue')['default']
    Slide: typeof import('./components/Slide.vue')['default']
    TobasketButton: typeof import('./components/TobasketButton.vue')['default']
    UndefinedWelcome: typeof import('./components/UndefinedWelcome.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
  }
}
